"""Regenerate <audit dir>/docs/coverage.md (local, not in git) from the built databases: what each producer's released
logs cover.

  uv run --locked --project scripts/audit_db python scripts/audit_db/gen_coverage.py [--audit-dir DIR]

Generated, never hand-edited: re-run after every rebuild so the page matches the data. It stays beside the databases:
per-producer coverage is working material, not part of the published schema and API guides.
"""
import argparse
from pathlib import Path

import duckdb

from paths import audit_dir, duck_temp

ap = argparse.ArgumentParser()
ap.add_argument("--audit-dir", help="directory holding the databases (default: paths.audit_dir())")
A = Path(ap.parse_args().audit_dir or audit_dir())
con = duckdb.connect(str(A / "derived.duckdb"), read_only=True)
con.execute(f"SET temp_directory='{duck_temp()}'")   # own spill dir: DuckDB's default <db>.tmp is shared by every reader
con.execute(f"ATTACH IF NOT EXISTS '{A / 'truth.duckdb'}' AS truth (READ_ONLY)")
con.execute("SET threads=4; SET memory_limit='4GB'")
q = lambda s, p=None: con.execute(s, p or []).fetchall()
built = dict(q("SELECT key, value FROM truth.build_info"))

out = ["# Coverage", "",
       f"Generated by `gen_coverage.py` from the databases built {built.get('built_at_utc')} "
       f"(repo inputs at `{built.get('repo_commit', '')[:9]}`). Do not edit by hand; re-run after a rebuild.", "",
       "Search times are UTC. A producer's network audit covers searches by **any** agency that touched its cameras; "
       "its own-search log covers only its own users' searches. Row counts include every release in full, so "
       "re-released months count more than once (see `release_content_groups`).", ""]
tot = q("""SELECT (SELECT count(*) FROM truth.flock_audit_rows), (SELECT count(*) FROM truth.smpd_pdf_rows),
                  (SELECT count(*) FROM truth.flock_event_rows), (SELECT count(*) FROM truth.releases),
                  (SELECT count(DISTINCT producer) FROM truth.releases)""")[0]
out += [f"Totals: {tot[0]:,} Flock audit rows, {tot[1]:,} SMPD PDF rows (one per search-id block; a search printed twice counts twice), {tot[2]:,} event-log rows, "
        f"{tot[3]:,} releases, {tot[4]} producers.", "",
        "## By producer and log type", "",
        "| Producer | Log | Releases | Rows | Searches from | Searches to | Released | Requests |",
        "|---|---|---:|---:|---|---|---|---|"]
rows = q("""
  WITH s AS (SELECT producer, audit, min(t) AS t0, max(t) AS t1 FROM sightings GROUP BY 1, 2),
  e AS (SELECT r.producer, 'event' AS audit, min(coalesce(flock_ts(e."Timestamp"), iso_ts_utc(e."Timestamp"))) t0,
               max(coalesce(flock_ts(e."Timestamp"), iso_ts_utc(e."Timestamp"))) t1
        FROM truth.flock_event_rows e JOIN truth.releases r USING (release_id) GROUP BY 1),
  r AS (SELECT producer, audit, count(*) n_rel, sum(n_rows) n, min(released_on) r0, max(released_on) r1,
               string_agg(DISTINCT pra_id, ', ' ORDER BY pra_id) pras FROM truth.releases GROUP BY 1, 2)
  SELECT r.producer, r.audit, r.n_rel, r.n, coalesce(s.t0, e.t0), coalesce(s.t1, e.t1), r.r0, r.r1, r.pras
  FROM r LEFT JOIN s USING (producer, audit) LEFT JOIN e USING (producer, audit)
  ORDER BY r.producer, r.audit""")
fmt = lambda d: d.strftime("%Y-%m-%d") if d else "?"
for p, a, nrel, n, t0, t1, r0, r1, pras in rows:
    rel = fmt(r0) if r0 == r1 else f"{fmt(r0)} – {fmt(r1)}"
    out.append(f"| {p} | {a} | {nrel} | {n:,} | {fmt(t0)} | {fmt(t1)} | {rel if r0 else 'not recorded'} | {pras} |")
out += ["", "`Searches from/to` come from parsed search times (`sightings.t`); for event logs, the event timestamps. "
        "`Released` is `releases.released_on` (MuckRock attachment date or a cited closed date); `not recorded` means unknown.", "",
        "## Rows the parser could not place in time", "",
        "| Producer | Rows with no `t` | Of rows | What the released `Search Time` cell holds |", "|---|---:|---:|---|"]
why = {p: w for p, w in q("""
  SELECT producer, string_agg(k || ' ' || format('{:,}', n), '; ' ORDER BY n DESC) FROM (
  SELECT r.producer, x.k, sum(x.n) AS n FROM (
    -- what the RELEASED cell under 'Search Time' holds (truth, not the layout-corrected field), for the rows derived
    -- could not place in time
    SELECT s.release_id, CASE WHEN nullif(trim(a."Search Time"), '') IS NULL THEN 'blank cell'
                              WHEN trim(a."Search Time") = '***' THEN 'masked as ***'
                              ELSE 'non-time text' END
                         || CASE WHEN s.layout_corrected THEN ' (row released under other column labels)' ELSE '' END AS k, count(*) n
    FROM sightings_flock s JOIN truth.flock_audit_rows a USING (release_id, row_no)
    WHERE s.t IS NULL GROUP BY 1, 2) x
  JOIN truth.releases r USING (release_id) GROUP BY 1, 2) GROUP BY 1""")}
for p, nnull, n in q("""SELECT producer, count(*) FILTER (WHERE t IS NULL), count(*) FROM sightings GROUP BY 1
                        HAVING count(*) FILTER (WHERE t IS NULL) > 0 ORDER BY 2 DESC"""):
    out.append(f"| {p} | {nnull:,} | {n:,} | {why.get(p, '')} |")
(A / "docs").mkdir(exist_ok=True)
(A / "docs" / "coverage.md").write_text("\n".join(out) + "\n")
print(f"wrote {A / 'docs' / 'coverage.md'} ({len(rows)} producer/log rows)")
