#!/usr/bin/env python3
"""Build a GitHub-issue body for discovery rejects awaiting triage.

``discover_articles.py --rejects-json`` records every URL dropped because
its domain isn't in ``assets/sources.json``. This script groups those by
domain, drops domains already triaged-as-skip in
``assets/articles/reject_ignore.json`` (aggregators, PR wires, off-topic
syndicators), and prints a markdown issue body to stdout.

Prints nothing (and exits 0) when nothing is pending, so the workflow can
close any open triage issue instead of posting an empty one.

Usage:
  uv run python scripts/discover_reject_issue.py /tmp/rejects.json
  uv run python scripts/discover_reject_issue.py rejects.json --max-examples 3
"""

import argparse
import functools
import json
import sys
from pathlib import Path

print = functools.partial(print, flush=True)

ROOT = Path(__file__).resolve().parent.parent
IGNORE_PATH = ROOT / "assets" / "articles" / "reject_ignore.json"


def normalize_domain(host: str) -> str:
    """Lowercase, strip a leading 'www.'. Keep other subdomains."""
    h = (host or "").strip().lower()
    return h[4:] if h.startswith("www.") else h


def load_ignored(path: Path) -> set[str]:
    if not path.exists():
        return set()
    try:
        data = json.loads(path.read_text())
    except json.JSONDecodeError:
        return set()
    return {normalize_domain(d) for d in data.get("ignored_domains", [])}


def is_ignored(domain: str, ignored: set[str]) -> bool:
    """True if domain equals, or is a subdomain of, any ignored apex."""
    d = normalize_domain(domain)
    if d in ignored:
        return True
    return any(d.endswith("." + apex) for apex in ignored)


def group_rejects(rejects: list[dict], ignored: set[str]) -> list[dict]:
    """Group non-ignored rejects by domain.

    Returns a list of {domain, count, urls, sources} sorted by count
    descending then domain. ``count`` is the number of rejected URLs;
    ``urls`` is de-duplicated; ``sources`` collects discovered_by labels."""
    groups: dict[str, dict] = {}
    for r in rejects:
        dom = normalize_domain(r.get("domain") or "")
        url = r.get("url") or ""
        if not dom or not url or is_ignored(dom, ignored):
            continue
        g = groups.setdefault(
            dom, {"domain": dom, "count": 0, "urls": [], "sources": set()}
        )
        g["count"] += 1
        if url not in g["urls"]:
            g["urls"].append(url)
        if r.get("discovered_by"):
            g["sources"].add(r["discovered_by"])
    return sorted(groups.values(), key=lambda g: (-g["count"], g["domain"]))


def render_body(groups: list[dict], max_examples: int = 3) -> str:
    """Markdown issue body, or "" when nothing is pending."""
    if not groups:
        return ""
    n = len(groups)
    lines = [
        f"## {n} domain{'s' if n != 1 else ''} awaiting triage",
        "",
        "Article discovery surfaced these domains that aren't in "
        "`assets/sources.json`, so their articles were dropped. For each, "
        "either:",
        "",
        "- **Add** it to `assets/sources.json` (with tier/stance) if it's a "
        "real outlet worth tracking, **or**",
        "- **Ignore** it by adding the apex to "
        "`assets/articles/reject_ignore.json` if it's an aggregator, PR "
        "wire, or off-topic syndicator.",
        "",
        "Handled domains drop off automatically on the next discovery run; "
        "this issue closes itself when nothing is left.",
        "",
    ]
    for g in groups:
        srcs = ", ".join(f"`{s}`" for s in sorted(g["sources"])) or "?"
        plural = "s" if g["count"] != 1 else ""
        lines.append(f"### `{g['domain']}` · {g['count']} hit{plural} "
                     f"· via {srcs}")
        for u in g["urls"][:max_examples]:
            lines.append(f"- {u}")
        extra = len(g["urls"]) - max_examples
        if extra > 0:
            lines.append(f"- …and {extra} more")
        lines.append("")
    lines.append(
        "<sub>Auto-generated by `scripts/discover_reject_issue.py` on each "
        "discovery run — edits are overwritten. Triage by editing "
        "`sources.json` or `reject_ignore.json`.</sub>"
    )
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("rejects_json",
                    help="path to discover_articles.py --rejects-json output")
    ap.add_argument("--max-examples", type=int, default=3,
                    help="example URLs to show per domain (default: 3)")
    ap.add_argument("--ignore-file", default=str(IGNORE_PATH),
                    help="path to reject_ignore.json")
    args = ap.parse_args()

    path = Path(args.rejects_json)
    if not path.exists():
        # No rejects file (e.g. dry-run) → treat as nothing pending.
        return 0
    try:
        rejects = json.loads(path.read_text()) or []
    except json.JSONDecodeError:
        print(f"could not parse {path}", file=sys.stderr)
        return 1

    ignored = load_ignored(Path(args.ignore_file))
    groups = group_rejects(rejects, ignored)
    body = render_body(groups, max_examples=args.max_examples)
    if body:
        sys.stdout.write(body + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
